### ISSUE TITLE
Add common structure for e2e tests for policies

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/policy-hub#132]
Define an e2e test structure for policies in every policy repository. The idea is that regardless of the chosen language/framework, e2e tests can be executed against the policy, by providing different test cases:

- Settings
- Request
- Expected Response
  - Mutate
  - Accept
  - Reject

By following the same structure on all policies, we can also link to the test cases on every policy in the Policy Hub, what will also constitute documentation for the policy itself, so the user can check if the policy behaves as they expect for all the specified cases. And also, since all policies share the same e2e test structure, the structure of the policy becomes well-known and helps to understand other policies.

**Comment by chrisns** [comment]
would be great to be able to use it as the primary form (and single source of truth) of documentation for the policies to save repetition and avoid yaml embedded in markdown falling out of sync.
Perhaps the policy hub can pull the bits together into a pretty render in time?

**Comment by flavio** [comment]
Closing right now, we will re-evaluate that in the future, based on user feedback
