### ISSUE TITLE
Sign all the policies created by kubewarden-developers using Sigstore

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-hub#133]
All the Kubewarden policies published on the policy hub must be signed using Sigstore.

## Acceptance criteria

* Each policy is signed using Sigstore, via the `cosign` cli
* The signature is performed using keyless signing
* There's a new release in Policy Hub

## Policies to be signed

  * [x] [kubewarden/user-group-psp-policy](https://github.com/kubewarden/user-group-psp-policy/pull/9)
  * [x] [kubewarden/seccomp-psp-policy
](https://github.com/kubewarden/seccomp-psp-policy/pull/9)  
  * [x] [kubewarden/selinux-psp-policy](https://github.com/kubewarden/selinux-psp-policy/pull/4)
  * [x] [kubewarden/allowed-proc-mount-types-psp-policy](https://github.com/kubewarden/allowed-proc-mount-types-psp-policy/pull/1)
  * [x] [kubewarden/allow-privilege-escalation-psp-policy](https://github.com/kubewarden/allow-privilege-escalation-psp-policy/pull/10)
  * [x] [kubewarden/volumes-psp-policy](https://github.com/kubewarden/volumes-psp-policy/pull/2)
  * [x] [kubewarden/sysctl-psp-policy](https://github.com/kubewarden/sysctl-psp-policy/pull/4)
  * [x] [kubewarden/readonly-root-filesystem-psp-policy](https://github.com/kubewarden/readonly-root-filesystem-psp-policy/pull/4)
  * [x] [kubewarden/host-namespaces-psp-policy](https://github.com/kubewarden/host-namespaces-psp-policy/pull/2)
  * [x] [kubewarden/hostpaths-psp-policy](https://github.com/kubewarden/hostpaths-psp-policy/pull/3)
  * [x] [kubewarden/capabilities-psp-policy](https://github.com/kubewarden/capabilities-psp-policy/pull/9)
  * [x] [kubewarden/flexvolume-drivers-psp-policy](https://github.com/kubewarden/flexvolume-drivers-psp-policy/pull/3)
  * [x] [kubewarden/apparmor-psp-policy](https://github.com/kubewarden/apparmor-psp-policy/pull/6)
  * [x] [kubewarden/allowed-fsgroups-psp-policy](https://github.com/kubewarden/allowed-fsgroups-psp-policy/pull/5)
  * [x] [kubewarden/disallow-service-loadbalancer-policy](https://github.com/kubewarden/disallow-service-loadbalancer-policy/pull/1)
  * [x] [kubewarden/disallow-service-nodeport-policy](https://github.com/kubewarden/disallow-service-nodeport-policy/pull/1)
  * [x] [kubewarden/safe-labels-policy](https://github.com/kubewarden/safe-labels-policy/pull/8)
  * [x] [kubewarden/safe-annotations-policy](https://github.com/kubewarden/safe-annotations-policy/pull/2)
  * [x] [kubewarden/ingress-policy](https://github.com/kubewarden/ingress-policy/pull/13)
  * [x] [kubewarden/trusted-repos-policy](https://github.com/kubewarden/trusted-repos-policy/pull/9)
  * [x] [kubewarden/pod-privileged-policy](https://github.com/kubewarden/pod-privileged-policy/pull/11)
  * [x] [kubewarden/pod-runtime-class-policy](https://github.com/kubewarden/pod-runtime-class-policy/pull/7)

**Comment by jvanz** [comment]
All the policies are signed and published in the Policy Hub
