### ISSUE TITLE
Feature Request: Show if policy has signature

### ISSUE THREAD

**Issue by viccuad** [kubewarden/policy-hub#173]
### Solution you'd like

Right now, we have signed policies in the Hub, but the Hub doesn't show any information on signatures.
Extend the Hub UI to show a "tick" (e.g: Twitter verified account) for those policies with signatures.

This may be done via the policy publishing workflow (as it has the image info, and can submit to the Hub with that info). Or maybe the Hub can look for image layers ending in .sig (eek). 

### To do list
- [x] https://github.com/kubewarden/policy-hub/pull/178
- [x] https://github.com/kubewarden/policy-hub/pull/179
- [x] https://github.com/kubewarden/notify-policy-hub/pull/1
- [x] https://github.com/kubewarden/github-actions/pull/27
- [x] [Add a workflow to periodic verify policies signatures.](https://github.com/kubewarden/policy-hub/pull/179)

**Comment by viccuad** [comment]
Writing a blogpost right now has made me wonder. Once this card is fully finished, it would be nice to have a very short blogpost announcing that it's live. WDYT?

**Comment by jvanz** [comment]
> Writing a blogpost right now has made me wonder. Once this card is fully finished, it would be nice to have a very short blogpost announcing that it's live. WDYT?

Yeap! This is a good idea. I'll create another issue to remember us about that.

**Comment by jvanz** [comment]
https://github.com/kubewarden/kubewarden.io/issues/85

**Comment by jvanz** [comment]
This bug has a spin off: https://github.com/kubewarden/policy-hub/issues/184.

But for now, it's done.
