### ISSUE TITLE
Untrusted policies marked as trusted.

### ISSUE THREAD

**Issue by jvanz** [kubewarden/policy-hub#184]
@kubewarden/kubewarden-developers , as I mentioned during a Kubewarden team call, I have some questions about the current approach. In the proposed  daily action to check if the policies are still trusted, the action just fail if some policies are not properly signed. Nothing more. This means that, if during a daily check a policy is not trusted anymore, the action will failed. But the policy will still show as "signed" in the policy hub. Which is not nice. With that in mind, I have two questions:

 1. Should the action mark the policy "signed = false" and update the website automatically?
 2. Should the action open an issue in the policy's repository to warn that it is not trusted anymore?

_Originally posted by @jvanz in https://github.com/kubewarden/policy-hub/issues/179#issuecomment-1113332882_

**Comment by viccuad** [comment]
I would happy with 1 for starters, given that we are only verifying kubewarden team policies for now.
