### ISSUE TITLE
Update policy hub landing page

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-hub#191]
We want to make our users aware that all the Kubewarden polices are now published on Artifact Hub.

We envisioned two possible ways to achieve that, it all depends on how complex it is to implement them.

# Banner (preferred solution)

Display a banner at the top of the page. The banner will state that all our policies are now on Artifact Hub. It will also have two links inside of it:
  * Link to the Artifact Hub page that shows all the Kubewarden policies. (For example, this is the [staging URL](https://staging.artifacthub.io/packages/search?kind=13&sort=relevance&page=1))
  * Link to the blog post where we announce this news

# Replace old landing page

Just show a static html page when visiting `hub.kubewarden.io`. The page will show the same information written above

**Comment by flavio** [comment]
CC @ncounter JFYI, we are moving away from Kubewarden Policy Hub up to Artifact Hub (official CNCF project).

Thanks a lot for your help with this website! :heart:

**Comment by ncounter** [comment]
> CC @ncounter JFYI, we are moving away from Kubewarden Policy Hub up to Artifact Hub (official CNCF project).
> 
> Thanks a lot for your help with this website! ❤️

I’m very glad this website has been part of the initial project and I want to believe it helped the project to take off its flight 😉. But moreover congratulations for being promoted to the upper and official level to the Artifact Hub. 🥳

**Comment by flavio** [comment]
Moved to blocked, we need to publish the blog post. This is going to happen tomorrow (July 22nd).

I'm going to take care of updating the links to the blog post and merging this PR. Thanks @jordojordo for the quick fix
