### ISSUE TITLE
Create PSP Volumes policy

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-hub#24]
Create a Kubewarden policy that can replace the [PSP Volumes](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#volumes-and-file-systems) one.

## Configuration

```yaml
allowedTypes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- secret
- projected
```

The policy takes the list of the allowed volume types using the `allowedTypes` setting. The special value `*` can be used to allow all kind of volumes.

The default value of `allowedTypes` is `[ ]`.

Settings validation:
* No other value can be specified together with `*`. For example, `allowedTypes: ['*', 'configMap']` is not a valid configuration setting.

**Comment by viccuad** [comment]
- [X] Create repo https://github.com/kubewarden/psp-sysctl-policy from the go template.
   - [X] Set GH Actions to "Require approval for all outside collaborators".
- [ ] Open PR with implementation: https://github.com/kubewarden/psp-hostpaths-policy/pull/1
   - [ ] Enabled GH Actions there to publish to ghcr.io
- [ ] Tag release once PR merged, check policy image when published:
- [ ] Add policy to Policyhub:

**Comment by flavio** [comment]
Done :partying_face:
