### ISSUE TITLE
Create `AllowedProcMountTypes` PSP

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-hub#30]
Create a Kubewarden policy that replaces [AllowedProcMountTypes PSP](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#allowedprocmounttypes)

### Configuration

```yaml
allowDefaultProcMountType: true
allowUnmaskedProcMountType: true
```

Default values:
* `allowDefaultProcMountType`: true
* `allowUnmaskedProcMountType`: false

These values are translated to strings, that are compared against `container.securityContext.procMount`:
* `allowDefaultProcMountType` -> `Default` string
* `allowUnmaskedProcMountType` -> `Unmasked` string

**Comment by ereslibre** [comment]
I propose to change the settings of this policy to `allowUnmaskedProcMountType: bool` only. The default is always granted, and a setting like `allowDefaultProcMountType: false` does not really apply.

The policy will only contain this boolean flag to allow `Unmasked` or not.

**Comment by ereslibre** [comment]
Policy: https://github.com/ereslibre/psp-allowed-proc-mount-types

**Comment by jvanz** [comment]
> Policy: https://github.com/ereslibre/psp-allowed-proc-mount-types

Besides some changes in the README where it's necessary removing  docs from the template repo, it's LGTM. I like the new approach for unit tests avoiding more files in the repository.

**Comment by viccuad** [comment]
I also like it, succinct, and no need to test serde parsing for the k8s_openapi::api objects on our own (looking forward to having this approach with tinygo).
