### ISSUE TITLE
Make context-aware policies prominent

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-hub#45]
Some policies can be "context-aware", these policies have `context-aware` key inside of their JSON definition:

```json
{
  "name": "foo",
  "description": "foo descr",
  "homepage": "https://github.com/kubewarden/foo",
  "author": {
    "name": "Kubewarden devs",
    "homepage": "https://github.com/kubewarden"
  },
  "download": {
    "registry": "ghcr.io/kubewarden/policies/foo:v0.1.8",
    "url": "https://github.com/kubewarden/foo/releases/download/v0.1.8/policy.wasm"
  },
  "keywords": [
    "foo"
  ],
  "resources": [
    "bar"
  ],
  "mutation": false,
  "context-aware": true
}
```

# To be done

* [ ] Update the `hub.json` files inside of our policies + the repo templates - @ereslibre is working on that
* [x] Update the website - @ncounter will work on that

**Comment by flavio** [comment]
In terms of icons, looking [here](https://material-ui.com/components/material-icons/#material-icons), I think these ones are nice:

| Context aware policy | NOT context aware policy|
|----------|-----|
| `CloudDownload` | `CloudOff` |
| `Sync` | `SyncDisabled` |
| `Wifi` | `WifiOff` |

I sorted them by preference, the cloud one if my favorite

**Comment by ncounter** [comment]
> In terms of icons, looking [here](https://material-ui.com/components/material-icons/#material-icons), I think these ones are nice:
> Context aware policy 	NOT context aware policy
> `CloudDownload` 	`CloudOff`
> `Sync` 	`SyncDisabled`
> `Wifi` 	`WifiOff`
> 
> I sorted them by preference, the cloud one if my favorite

What does `context-aware` flag represent/what is the meaning in this context? By the name itself and the common known meaning I would propose alternatives:
- `Visibility`|`VisibilityOff` (it's an eye)
- `BlurOn`|`BlurOff` (
- `Business`|`DomainDisabled`
- `CenterFocusStrong`|`CenterFocusWeak`

something like _the policy has view/knowledge to take decisions depending on the context_ . What do you think? Otherwise, the cloud one is my favorite too.
Btw, the idea would be to place the new icon closed to the `mutation` one, would it be ok? In case the flag it's true I'd go for a green or blue color, in case it's false I'd go with dark-gray instead.

**Comment by kkaempf** [comment]
Everything is 'cloud' these days.

I wonder what 'context-aware' tells the policy user ? Why would a user need to know ? How does a user's behavior change with that knowledge ?

**Comment by flavio** [comment]
`context-aware` is a term that was coined by OPA, which features also on different k8s books.

The concept is: a `context-aware` policy has awareness of other resources already defined inside of the cluster. This is opposed to regular policies which have 0 knowledge of what is going on inside of the cluster, they can only see the incoming object to be evaluated.

Proceeding with my stream of thoughts: regular policies can be seen like in "airplane mode", while context-aware ones are "connected" to the network. Thinking more about that, maybe the `sync` icons are the best fit :man_shrugging:

**Comment by kkaempf** [comment]
I'm aware of the meaning of "context-aware". :wink:
But I'm not sure if a regular _user_ of a policy needs to know if a policy is context-aware or not.

As a user, I'm interested in the semantics of a policy. What does it check ? Which user-settable parameters does it accept ? etc.
I'm (probably) not interested in _how_ the policy implements its checks and how the policy collects its data.

**Comment by ereslibre** [comment]
As a security-focused user, I would say it is good to show this information clearly. Despite Wasm is already a very safe environment, a user might be interested in only installing policies that are not able to fetch any kind of external information, and only take decisions based on the resource it is evaluating.

**Comment by ncounter** [comment]
JFYI I forgot to update the status here: the UI part is already implemented and published since June. I'm not sure about the template though, but maybe this can be closed or?

**Comment by ereslibre** [comment]
Thank you @ncounter. I think we can close this issue. We still have to do the last stretch with context-aware policies.

Let's close this and reopen if necessary.
