### ISSUE TITLE
Hub: use new artwork

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-hub#6]
We should update the policy hub website to use the new artwork we got.

# Acceptance criteria

* The new logo is used: https://github.com/rancher/project-assets/tree/master/logos
* The new color palette is used: https://github.com/rancher/project-assets/blob/master/colors/colors.md#kubewarden

**Comment by flavio** [comment]
@ncounter this is something where we need your help :pleading_face:

**Comment by ncounter** [comment]
@flavio booked. Any due date?

PS: I updated the issue description with the color palette link :wink:

**Comment by flavio** [comment]
We should get it done by the end of this month. KubeCon begins on the 4th of May

**Comment by ncounter** [comment]
Addressed in https://github.com/kubewarden/policy-hub/commit/e2c92cc54c71c5e05f436c63e4217ed8ce239164
