### ISSUE TITLE
Adapt policies that match containers and init containers to take ephemeral containers into account

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/policy-hub#82]
[Ephemeral containers](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/) is a new feature that allows ephemeral containers to be created inside an existing Pod, so it's easier to debug running applications while reusing the same namespaces as the application to observe.

Many of our policies targeting pods take `containers` and `initContainers` into account when evaluating a pod.

The `ephemeralContainers` attribute is ignored during the pod creation or modification. This behavior is similar to what happens to the `status` subresource: it is ignored when created or updated.

The way to create ephemeral containers in an existing pod is by using the dedicated `/ephemeralcontainers` pod API subresource.

This task is also to investigate what would be the best way to [protect the `/ephemeralcontainers` endpoint, that can be used to create ephemeral containers in an existing pod](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#-strong-ephemeralcontainers-operations-pod-v1-core-strong-).

More information about ephemeral containers: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/277-ephemeral-containers/README.md

**Comment by flavio** [comment]
Closing, we will tackle that on a per-policy basis depending on user feedback
