### ISSUE TITLE
Filtering with `safe` doesn't lead to the expected result

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-hub#83]
How to reproduce:

- Enter `safe` into the search box
- No policy is returned
- Enter `labels`
- The `safe-labels` policy is returned

I would have expected `safe-labels` and `safe-annotations` to be returned when doing a search with `safe`.

**Comment by flavio** [comment]
ping @ncounter

**Comment by ncounter** [comment]
@flavio actually, as the filter placeholder says, the filtering is applied on the "description" metadata only, and apparently there is no *safe* word in the description of those two policies, it is mentioned in the name only.

```
name: safe-annotations
description: A policy that validates Kubernetes' resource annotations
```
```
name: safe-labels
description: A policy that validates Kubernetes' resource labels
```


Now, the question: do you feel it'd be better to filter on both `title` and `description` at the same time, or better to keep the filtering applied on the `description` field only?

**Comment by flavio** [comment]
Oh, you're right. I think we should leave things as they currently are.

Closing as invalid
