### ISSUE TITLE
Contribute to https://github.com/appvia/psp-migration so all PSP's implemented by Kubewarden are reported in the table

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/policy-hub#90]

**Comment by jvanz** [comment]
@chrisns updated the Kubewarden files adding almost [every missing policy.](https://github.com/appvia/psp-migration/commit/62031aa5c35afba008707ae2d60b93a483c198ea) .

The two missing ones is the recent [policy](https://github.com/kubewarden/readonly-root-filesystem-psp-policy) created by @flavio, and the seccomp one. AFAICS, we do not have a seccomp policy yet and I'll update the `psp-migration` repository with the `readonly-root-filesystem-psp-policy`.

**Comment by jvanz** [comment]
https://github.com/appvia/psp-migration/pull/1

**Comment by jvanz** [comment]
https://github.com/kubewarden/policy-hub/issues/109

**Comment by jvanz** [comment]
Moving this to block until we close [this]( https://github.com/kubewarden/policy-hub/issues/109)

**Comment by jvanz** [comment]
Blocked by https://github.com/kubewarden/seccomp-psp-policy/issues/6

**Comment by ereslibre** [comment]
We can close this already. This is mostly done, and communication with the maintainers of the psp-migration tool is open.
